sudo: false
script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker build -t django-container .
- docker images
- docker tag django-container "$DOCKER_USERNAME/django-container:$TRAVIS_BRANCH"
- docker images
  # - docker push $DOCKER_USERNAME/django-container
