sudo: false
langauge: python
python:
  - 3.6
before_script:
  - pip install django
  - pip install nose2
script:
  - nose2
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t django-container .
  - FIXED_BRANCH=$(echo $TRAVIS_BRANCH | tr / -)
  - docker tag django-container "$DOCKER_USERNAME/django-container:$FIXED_BRANCH"
  - docker push "$DOCKER_USERNAME/django-container:$FIXED_BRANCH"
  - docker images
