import os


APPLICATION_CERT_PATH = os.getenv('CERT_PATH', '')
APPLICATION_KEY_PATH = os.getenv('KEY_PATH', '')
RESTCLIENTS_CA_BUNDLE = '/app/certs/ca-bundle.crt'
RESTCLIENTS_DAO_CACHE_CLASS = os.getenv('CACHE_CLASS', '')
RESTCLIENTS_DEFAULT_TIMEOUT = 2
RESTCLIENTS_DEFAULT_POOL_SIZE = 10
RESTCLIENTS_DEFAULT_ENVS = ['PROD', 'EVAL']

if os.getenv('CACHE', '') == 'memcached':
    RESTCLIENTS_DAO_CACHE_CLASS = 'myuw.util.cache_implementation.MyUWMemcachedCache'
    RESTCLIENTS_MEMCACHED_SERVERS = (
        os.getenv('CACHE_NODE_0', '') + ':' + os.getenv('CACHE_PORT', '11211'),
        os.getenv('CACHE_NODE_1', '') + ':' + os.getenv('CACHE_PORT', '11211'),
    )

if os.getenv('GWS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_GWS_DAO_CLASS = 'Live'
    RESTCLIENTS_GWS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_GWS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('GWS_ENV') == 'PROD':
        RESTCLIENTS_GWS_HOST = 'https://groups.uw.edu'
    else:
        RESTCLIENTS_GWS_HOST = 'https://iam-ws.u.washington.edu:7443'

if os.getenv('SWS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_SWS_DAO_CLASS = 'Live'
    RESTCLIENTS_SWS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_SWS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('SWS_ENV') == 'PROD':
        RESTCLIENTS_SWS_HOST = 'https://ws.admin.washington.edu:443'
    else:
        RESTCLIENTS_SWS_HOST = 'https://wseval.s.uw.edu:443'

if os.getenv('PWS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_PWS_DAO_CLASS = 'Live'
    RESTCLIENTS_PWS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_PWS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('PWS_ENV') == 'PROD':
        RESTCLIENTS_PWS_HOST = 'https://ws.admin.washington.edu:443'
    else:
        RESTCLIENTS_PWS_HOST = 'https://wseval.s.uw.edu:443'

if os.getenv('KWS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_KWS_DAO_CLASS = 'Live'
    RESTCLIENTS_KWS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_KWS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('KWS_ENV') == 'PROD':
        RESTCLIENTS_KWS_HOST = 'https://ws.admin.washington.edu:443'
    else:
        RESTCLIENTS_KWS_HOST = 'https://wseval.s.uw.edu:443'

if os.getenv('HRPWS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_HRPWS_DAO_CLASS = 'Live'
    RESTCLIENTS_HRPWS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_HRPWS_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_HRPWS_TIMEOUT = os.getenv('HRPWS_TIMEOUT', RESTCLIENTS_DEFAULT_TIMEOUT)
    if os.getenv('HRPWS_ENV') == 'PROD':
        RESTCLIENTS_HRPWS_HOST = 'https://ws.admin.washington.edu:443'
    else:
        RESTCLIENTS_HRPWS_HOST = 'https://wseval.s.uw.edu:443'

if os.getenv('NWS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_NWS_DAO_CLASS = 'Live'
    RESTCLIENTS_NWS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_NWS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('NWS_ENV') == 'PROD':
        RESTCLIENTS_NWS_HOST = 'https://api.concert.uw.edu'
    else:
        RESTCLIENTS_NWS_HOST = 'https://api.test.concert.uw.edu'

if os.getenv('UWNETID_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_UWNETID_DAO_CLASS = 'Live'
    RESTCLIENTS_UWNETID_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_UWNETID_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_UWNETID_TIMEOUT = os.getenv('UWNETID_TIMEOUT', 55)
    RESTCLIENTS_UWNETID_HOST = 'https://uwnetid.washington.edu'
    if os.getenv('UWNETID_ENV') == 'EVAL':
        RESTCLIENTS_UWNETID_VERSION = 'v0-eval'

if os.getenv('CANVAS_ENV') in ['PROD', 'EVAL', 'BETA']:
    RESTCLIENTS_CANVAS_DAO_CLASS = 'Live'
    RESTCLIENTS_CANVAS_OAUTH_BEARER = os.getenv('CANVAS_OAUTH_BEARER', '')
    RESTCLIENTS_CANVAS_ACCOUNT_ID = os.getenv('CANVAS_ACCOUNT_ID')
    RESTCLIENTS_CANVAS_TIMEOUT = os.getenv('CANVAS_TIMEOUT', RESTCLIENTS_DEFAULT_TIMEOUT)
    if os.getenv('CANVAS_ENV') == 'PROD':
        RESTCLIENTS_CANVAS_HOST = 'https://canvas.uw.edu'
    elif os.getenv('CANVAS_ENV') == 'EVAL':
        RESTCLIENTS_CANVAS_HOST = 'https://uw.test.instructure.com'
    else:
        RESTCLIENTS_CANVAS_HOST = 'https://uw.beta.instructure.com'

if os.getenv('CODA_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_CODA_DAO_CLASS = 'Live'
    RESTCLIENTS_CODA_AUTH_TOKEN = os.getenv('CODA_AUTH_TOKEN', '')
    if os.getenv('CODA_ENV') == 'PROD':
        RESTCLIENTS_CODA_HOST = 'https://coda.uw.edu'
    else:
        RESTCLIENTS_CODA_HOST = 'https://coda-test.uw.edu'

if os.getenv('CATALYST_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_CATALYST_DAO_CLASS = 'Live'
    if os.getenv('CATALYST_PRIVATE_KEY') is not None:
        RESTCLIENTS_CATALYST_SOL_AUTH_PUBLIC_KEY = os.getenv('CATALYST_PUBLIC_KEY')
        RESTCLIENTS_CATALYST_SOL_AUTH_PRIVATE_KEY = os.getenv('CATALYST_PRIVATE_KEY')
    else:
        RESTCLIENTS_CATALYST_CERT_FILE = APPLICATION_CERT_PATH
        RESTCLIENTS_CATALYST_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('CATALYST_ENV') == 'PROD':
        RESTCLIENTS_CATALYST_HOST = 'https://catalyst.uw.edu'
    else:
        RESTCLIENTS_CATALYST_HOST = 'https://cat-dev-tools11.s.uw.edu'

if os.getenv('GRADEPAGE_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_GRADEPAGE_DAO_CLASS = 'Live'
    if os.getenv('GRADEPAGE_ENV') == 'PROD':
        RESTCLIENTS_GRADEPAGE_HOST = 'https://gradepage.uw.edu'
    else:
        RESTCLIENTS_GRADEPAGE_HOST = 'https://gradepage-test.s.uw.edu'

if os.getenv('BOOKSTORE_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_BOOKSTORE_DAO_CLASS = 'Live'
    RESTCLIENTS_BOOKSTORE_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_BOOKSTORE_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_BOOKSTORE_HOST = 'https://www7.bookstore.washington.edu'

if os.getenv('GRAD_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_GRAD_DAO_CLASS = 'Live'
    RESTCLIENTS_GRAD_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_GRAD_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('GRAD_ENV') == 'PROD':
        RESTCLIENTS_GRAD_HOST = 'https://webapps.grad.uw.edu'
    else:
        RESTCLIENTS_GRAD_HOST = 'https://testweb.grad.uw.edu'

if os.getenv('MYPLAN_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_MYPLAN_DAO_CLASS = 'Live'
    RESTCLIENTS_MYPLAN_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_MYPLAN_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('MYPLAN_ENV') == 'PROD':
        RESTCLIENTS_MYPLAN_HOST = 'https://ws.uwstdent.washington.edu'
    else:
        RESTCLIENTS_MYPLAN_HOST = 'https://ws-eval.uwstudent.washington.edu'

if os.getenv('LIBCURRICS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_LIBCURRICS_DAO_CLASS = 'Live'
    RESTCLIENTS_LIBCURRICS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_LIBCURRICS_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_LIBCURRICS_HOST = 'https://currics.lib.washington.edu'

if os.getenv('LIBRARIES_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_LIBRARIES_DAO_CLASS = 'Live'
    RESTCLIENTS_LIBRARIES_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_LIBRARIES_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_LIBRARIES_HOST = 'https://mylibinfo.lib.washington.edu'

if os.getenv('CALENDAR_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_CALENDAR_DAO_CLASS = 'Live'
    RESTCLIENTS_CALENDAR_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_CALENDAR_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_CALENDAR_HOST = 'https://www.trumba.com'

if os.getenv('SDBMYUW_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_SDBMYUW_DAO_CLASS = 'Live'
    if os.getenv('SDBMYUW_ENV') == 'PROD':
        RESTCLIENTS_SDBMYUW_HOST = 'https://sdb.admin.uw.edu'
    else:
        RESTCLIENTS_SDBMYUW_HOST = 'https://it-eval.s.uw.edu'

if os.getenv('HFS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_HFS_DAO_CLASS = 'Live'
    RESTCLIENTS_HFS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_HFS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('HFS_ENV') == 'PROD':
        RESTCLIENTS_HFS_HOST = 'https://api.hfs.washington.edu'
    else:
        RESTCLIENTS_HFS_HOST = 'https://tapi.washington.edu'

if os.getenv('ADSEL_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_ADSEL_DAO_CLASS = 'Live'
    RESTCLIENTS_ADSEL_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_ADSEL_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('ADSEL_ENV') == 'PROD':
        RESTCLIENTS_ADSEL_HOST = 'https://adselapi.uw.edu'
    else:
        RESTCLIENTS_ADSEL_HOST = 'https://test.adselapi.uw.edu'

if os.getenv('UPASS_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_UPASS_DAO_CLASS = 'Live'
    RESTCLIENTS_UPASS_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_UPASS_KEY_FILE = APPLICATION_KEY_PATH
    if os.getenv('UPASS_ENV') == 'PROD':
        RESTCLIENTS_UPASS_HOST = 'https://wscc.admin.uw.edu'
    else:
        RESTCLIENTS_UPASS_HOST = 'https://eval-wscc.admin.uw.edu'

if os.getenv('IASYSTEM_UW_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_IASYSTEM_UW_DAO_CLASS = 'Live'
    RESTCLIENTS_IASYSTEM_UW_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_IASYSTEM_UW_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_IASYSTEM_UW_HOST = 'https://uw.iasystem.org'

if os.getenv('IASYSTEM_UWB_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_IASYSTEM_UWB_DAO_CLASS = 'Live'
    RESTCLIENTS_IASYSTEM_UWB_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_IASYSTEM_UWB_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_IASYSTEM_UWB_HOST = 'https://uwb.iasystem.org'

if os.getenv('IASYSTEM_UWT_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_IASYSTEM_UWT_DAO_CLASS = 'Live'
    RESTCLIENTS_IASYSTEM_UWT_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_IASYSTEM_UWT_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_IASYSTEM_UWT_HOST = 'https://uwt.iasystem.org'

if os.getenv('IASYSTEM_UWEO_AP_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_IASYSTEM_UWEO_AP_DAO_CLASS = 'Live'
    RESTCLIENTS_IASYSTEM_UWEO_AP_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_IASYSTEM_UWEO_AP_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_IASYSTEM_UWEO_AP_HOST = 'https://uweo-ap.iasystem.org'

if os.getenv('IASYSTEM_UWEO_IELP_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_IASYSTEM_UWEO_IELP_DAO_CLASS = 'Live'
    RESTCLIENTS_IASYSTEM_UWEO_IELP_CERT_FILE = APPLICATION_CERT_PATH
    RESTCLIENTS_IASYSTEM_UWEO_IELP_KEY_FILE = APPLICATION_KEY_PATH
    RESTCLIENTS_IASYSTEM_UWEO_IELP_HOST = 'https://uweo-ielp.iasystem.org'

if os.getenv('ASTRA_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    ASTRA_CERT = APPLICATION_CERT_PATH
    ASTRA_KEY = APPLICATION_KEY_PATH
    ASTRA_APPLICATION = os.getenv('ASTRA_APPLICATION', '')
    ASTRA_ENVIRONMENT = os.getenv('ASTRA_ENV')
    if os.getenv('ASTRA_ENV') == 'PROD':
        ASTRA_WSDL = 'https://astra.admin.uw.edu/astraws/v2/default.asmx?wsdl'
    else:
        ASTRA_WSDL = 'https://eval-astra.admin.uw.edu/astraws/v2/default.asmx?wsdl'

if os.getenv('R25_ENV') in RESTCLIENTS_DEFAULT_ENVS:
    RESTCLIENTS_R25_DAO_CLASS = 'Live'
    RESTCLIENTS_R25_INSTANCE = 'washington'
    RESTCLIENTS_R25_SSL_VERSION = 'TLSv1_2'
    RESTCLIENTS_R25_BASIC_AUTH = os.getenv('R25_BASIC_AUTH', '')
    RESTCLIENTS_R25_HOST = 'https://webservices.collegenet.com'

MEMCACHED_SERVER_COUNT = int(os.getenv('MEMCACHED_SERVER_COUNT', 0))
if MEMCACHED_SERVER_COUNT > 0:
    MEMCACHED_SERVER_SPEC = os.getenv('MEMCACHED_SERVER_SPEC')
    RESTCLIENTS_MEMCACHED_SERVERS = tuple(MEMCACHED_SERVER_SPEC.format(n)
                                          for n in range(
                                                  MEMCACHED_SERVER_COUNT))
